# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:categories/:title.html
paginate: 5
port: 3000
safe: true
comments: true


# edit here to achieve your personal greatness
<<<<<<< HEAD
name: Jigar Lodaya
=======
>>>>>>> gh-pages
disqus: jigs12
url: jigarlodaya.me
baseurl: /
title: Jigar Lodaya
author: Jigar Lodaya
description: Personal blog and resume
avatar: profile.png
email: mailme@jigarlodaya.me
github: jigs1212
twitter: jigs1212
linkedin:
google_analytics:
email_full: mailto:mailme@jigarlodaya.me
tel: +91 7736 569688
tel_full: tel:+917736569688
google_maps:
address: 9/17 BEACH ROAD
postcode: 673001
city: Kozhikode / Calicut
state: Kerala
country: India
